name:                herms
version:             0.1.0.0
homepage:            https://github.com/JackKiefer/herms#readme
license:             GPL-3
author:              Jack Kiefer
maintainer:          jack.c.kiefer@gmail.com
copyright:           2017, Jack Kiefer
category:            Command Line Tool
extra-source-files:
- README.md

#     >= 0.17 && < 0.20
dependencies:
  - base      >= 4.7 && < 5
  - blaze-markup
  - brick
  - directory
  - microlens >= 0.4.8.0 && < 0.5
  - microlens-th
  - monad-logger
  - persistent
  - persistent-sqlite
  - persistent-template
  - resource-pool
  - resourcet
  - safe
  - shakespeare
  - split     >= 0.2.3 && < 0.3
  - text
  - vty       >= 5.15.0 && < 5.16

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DeriveDataTypeable
  - DeriveGeneric
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NoMonomorphismRestriction
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

library:
  source-dirs: src
  exposed-modules:
    - Herms

executables:
  herms:
    dependencies:
      - herms
    source-dirs:      app
    main:             Main.hs
